### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.hub'; 'torch' is not a package

### ISSUE THREAD

**Issue by and0802** [KentoNishi/torch-pitch-shift#3]
hello sir, i try to install your repo and i get this error when i run your python program :

ModuleNotFoundError: No module named 'torch.hub'; 'torch' is not a package

i use this req version:
torch 1.13.0
torchaudio 0.13.0

I try to install torch 1.7.0 like your req, but error massage showed. The massage Like i can't found that version (1.7.0).
Can you help me for solve this problem sir?

thankyou sir. I really appreciate your help. :)

**Comment by and0802** [comment]
> hello sir, i try to install your repo and i get this error when i run your python program :
> 
> ModuleNotFoundError: No module named 'torch.hub'; 'torch' is not a package
> 
> i use this req version: torch 1.13.0 torchaudio 0.13.0
> 
> I try to install torch 1.7.0 like your req, but error massage showed. The massage Like i can't found that version (1.7.0). Can you help me for solve this problem sir?
> 
> thankyou sir. I really appreciate your help. :)

solved sir, thats my bad for giving python program title torch.py XD

**Comment by KentoNishi** [comment]
Sorry for the late response! I'm glad you solved it.
