### ISSUE TITLE
setup.py fails due to missing readme.me in pypi source bundle 

### ISSUE THREAD

**Issue by FriederikeBrezing** [KentoNishi/torch-pitch-shift#4]
The source bundle in pypi does not contain the readme.md which causes setup.py to fail.

How to replicate: 
Download https://files.pythonhosted.org/packages/source/t/torch-pitch-shift/torch_pitch_shift-1.2.2.tar.gz and unpack

Run python setup.py.

Error message: 

File "XXXX/torch-pitch-shift/torch_pitch_shift-1.2.2/setup.py", line 4, in <module>
    with open("readme.md", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'

**Comment by KentoNishi** [comment]
resolved in [v1.2.3](https://github.com/KentoNishi/torch-pitch-shift/releases/tag/v1.2.3)!

**Comment by FriederikeBrezing** [comment]
Thanks for the quick fix! Unfortunately, there are still some issues: https://github.com/KentoNishi/torch-pitch-shift/issues/6 and https://github.com/KentoNishi/torch-pitch-shift/issues/7
