### ISSUE TITLE
setup.py requires additional argument which makes it difficult to install from source via pip

### ISSUE THREAD

**Issue by FriederikeBrezing** [KentoNishi/torch-pitch-shift#7]
The setup.py script requires additional arguments which make it difficult to pip install torch-pitch-shift from source.

(We are trying to build a conda package for torch-pitch-shift, with conda build running pip install on the source.)

After manually fixing https://github.com/KentoNishi/torch-pitch-shift/issues/6 by downloading the requirements.txt file and creating new tar.gz file we get the following error: 

```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
     XXX/setuptools/dist.py:543: UserWarning: The version specified ('egg_info') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: option --egg-base not recognized
      egg_info
      [end of output]

```

To replicate: 
Download https://files.pythonhosted.org/packages/source/t/torch-pitch-shift/torch_pitch_shift-1.2.3.tar.gz and unpack.
Download https://github.com/KentoNishi/torch-pitch-shift/blob/ba66e5e43cfe6748fd0af9de37b39d63c40d0be4/requirements.txt (into same location). 

Run `pip install PATH/TO/SOURCE`.

How we can pip install torch-pitch-shift from source?

**Comment by KentoNishi** [comment]
hm, i'm not really sure what the issue is here. i can reproduce it, but i have no idea how to solve it. help would be appreciated.

**Comment by KentoNishi** [comment]
@FriederikeBrezing try v1.2.4 and let me know if it works
