### ISSUE TITLE
Global Warnings Suppression

### ISSUE THREAD

**Issue by ramppdev** [KentoNishi/torch-pitch-shift#8]
When using `torch-pitch-shift`, all warnings are completely disabled here:
https://github.com/KentoNishi/torch-pitch-shift/blob/04cf7afd6b2d161063f115ba068b1f68f3eedc50/torch_pitch_shift/main.py#L16

By using `warnings.simplefilter("ignore")` without any scope limitation, all warnings from any imported libraries or subsequent code execution (after importing `torch-pitch-shift`) are completely disabled.
This could suppress important warnings from other libraries or tools that rely on the package and make debugging difficult for users.

Is this an intended behavior or could the suppression be scoped?

**Comment by KentoNishi** [comment]
good catch. i'm tied up with things at the moment, if you could submit a pr i'd be happy to merge and release!
